// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9U4qGKHVtkjVkeOCZW63cM9s9Z6ncmM8',
    appId: '1:959154953764:web:7524965ebf201ce1ad02b1',
    messagingSenderId: '959154953764',
    projectId: 'kindergarden-e249d',
    authDomain: 'kindergarden-e249d.firebaseapp.com',
    storageBucket: 'kindergarden-e249d.appspot.com',
    measurementId: 'G-Z6DBS1TCGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOq-FQd6vYqKPtz1OnmFhx_dHT9_6M5Lw',
    appId: '1:959154953764:android:00dac5d5180c81adad02b1',
    messagingSenderId: '959154953764',
    projectId: 'kindergarden-e249d',
    storageBucket: 'kindergarden-e249d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWJKG64062WwGQ6gBnyiKec4lgBLY_FM',
    appId: '1:959154953764:ios:00849abc417c9f6cad02b1',
    messagingSenderId: '959154953764',
    projectId: 'kindergarden-e249d',
    storageBucket: 'kindergarden-e249d.appspot.com',
    iosClientId: '959154953764-homa5gk8i4krm6loj5kmoljb52vvgiem.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWJKG64062WwGQ6gBnyiKec4lgBLY_FM',
    appId: '1:959154953764:ios:00849abc417c9f6cad02b1',
    messagingSenderId: '959154953764',
    projectId: 'kindergarden-e249d',
    storageBucket: 'kindergarden-e249d.appspot.com',
    iosClientId: '959154953764-homa5gk8i4krm6loj5kmoljb52vvgiem.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBasics',
  );
}
